import { DigestPayload } from '../types/index.ts';

export const SAMPLE_DAILY_DIGEST: DigestPayload = {
  date: 'Jan 15, 2025',
  emailSubject: "Dealhunter X: your Top 3 trade ideas for Jan 15, 2025",
  tagline: "Find tomorrow's ten-baggers, today.",
  callCount: 6,
  estimatedCostUSD: '$0.0024',
  signOff: 'Dealhunter X',
  footerDisclaimer:
    "Dealhunter X is for education only. Not financial advice. Trade ideas are generated by AI from public sources and may be wrong. The tagline describes you can delegate tasks, but not responsibility.",
  sourcesConsulted: ['polymarket', 'social', 'fmp'],
  unavailableSources: [],
  riskCheck: {
    overallRiskLevel: 'High',
    objectiveEvaluation:
      'Targeting asymmetric 10X returns requires concentrated exposure to high-beta momentum catalysts. Capital preservation is critical because short-term volatility can induce up to 30% drawdowns prior to continuation.',
    downsideBuffer:
      'Strict stop-loss recommended at 7% to 9% below volume-weighted average entry price.',
    volatilityFlag:
      'High beta detected across tech and biopharma sectors. Expect elevated implied volatility into upcoming earnings.',
    capitalPreservationNote:
      'Never allocate more than 25% of overall capital to a single catalyst. Size positions proportionally to withstand market-wide corrections.',
  },
  ideas: [
    {
      id: 'sample-1',
      ticker: 'NVDA',
      exchange: 'NASDAQ',
      direction: 'LONG',
      thesis:
        'Next-generation accelerator deployment orders are accelerating faster than supply constraints indicate. Social developer sentiment and prediction market odds reflect an imminent enterprise upgrade cycle.',
      entryRationale:
        'Scale in on pullbacks towards the 20-day exponential moving average with institutional volume absorption.',
      suggestedPositionSizePercent: 25,
      suggestedCapitalAmountUSD: 250,
      timeHorizon: '1 Month',
      keyRisk:
        'Export regulation adjustments and semiconductor supply chain bottleneck announcements.',
      bullets: [
        'Polymarket prediction contracts pricing a 78% likelihood of quarterly enterprise datacenter revenue beating consensus by >12%.',
        'Social Superpowers sentiment radar detected a +340% surge in developer discussions across AI engineering communities over the past 12 hours.',
        'Financial Modeling Prep signals robust forward free cash flow margins exceeding 45%, providing valuation support against speculative pullbacks.',
      ],
      citedSources: [
        {
          mcpName: 'PolymarketScan',
          itemTitle: 'Q1 AI Datacenter Hardware CapEx Growth Over Expectations (>78% YES)',
        },
        {
          mcpName: 'Social Superpowers',
          itemTitle: 'Enterprise GPU cluster deployment momentum and chatter volume spike (+340%)',
        },
        {
          mcpName: 'Financial Modeling Prep',
          itemTitle: 'NVDA Margin and Volume Profile: 52-Week Relative Strength Index in accumulation zone',
        },
      ],
    },
    {
      id: 'sample-2',
      ticker: 'LLY',
      exchange: 'NYSE',
      direction: 'LONG',
      thesis:
        'Recent positive phase clinical trial updates for oral metabolic formulations are generating strong institutional re-ratings. Mainstream search volume confirms widespread consumer adoption and insurance policy approvals.',
      entryRationale:
        'Initiate long position on consolidation break above recent resistance channel.',
      suggestedPositionSizePercent: 20,
      suggestedCapitalAmountUSD: 200,
      timeHorizon: '1 Month',
      keyRisk:
        'Regulatory delays in manufacturing plant expansions and competing pipeline trials.',
      bullets: [
        'Social momentum and market signals highlight international healthcare approval accelerated pathways in European jurisdictions.',
        'Social buzz and patient advocacy community sentiment index reached 91/100 following published peer-reviewed outcomes.',
        'Market data from FMP confirms consecutive quarterly guidance upgrades and strong institutional accumulation volume.',
      ],
      citedSources: [
        {
          mcpName: 'Social Superpowers',
          itemTitle: 'Breakthrough metabolic clinical readout viral discussion and regulatory consideration',
        },
        {
          mcpName: 'Social Superpowers',
          itemTitle: 'Patient treatment adherence metrics and viral consumer interest expansion',
        },
        {
          mcpName: 'Financial Modeling Prep',
          itemTitle: 'LLY Balance Sheet Quality: Return on Invested Capital exceeding 22%',
        },
      ],
    },
    {
      id: 'sample-3',
      ticker: 'PLTR',
      exchange: 'NYSE',
      direction: 'LONG',
      thesis:
        'Commercial enterprise bootcamp conversions and public sector defense renewals are driving sequential revenue acceleration. Retail momentum and prediction sentiment remain firmly tilted to continued operating leverage.',
      entryRationale:
        'Enter on intraday retest of primary volume shelf support level.',
      suggestedPositionSizePercent: 15,
      suggestedCapitalAmountUSD: 150,
      timeHorizon: '1 Month',
      keyRisk:
        'High valuation multiples leave share price vulnerable to broad macroeconomic rate shifts.',
      bullets: [
        'Social media tracking shows mention volume elevated by +210% week-over-week following new multi-year defense IT integration announcements.',
        'Polymarket sentiment contracts indicate 72% probability of continued double-digit US commercial enterprise customer additions.',
        'FMP operational metrics demonstrate Rule of 40 performance with accelerating GAAP operating margin expansion.',
      ],
      citedSources: [
        {
          mcpName: 'Google News',
          itemTitle: 'Defense intelligence and automated analytics procurement expansion announced',
        },
        {
          mcpName: 'Social Superpowers',
          itemTitle: 'Commercial AIP deployment case studies trending across enterprise tech forums (+210%)',
        },
        {
          mcpName: 'PolymarketScan',
          itemTitle: 'Federal and NATO analytics infrastructure modernization contract awards',
        },
      ],
    },
  ],
};
